### ISSUE TITLE
Execution of 'brew install boxen/brews/nginx --with-http2 fails

### ISSUE THREAD

**Issue by happicamper** [boxen/puppet-nginx#50]
My Boxen fails with this error output:
```
Already downloaded: /opt/boxen/cache/homebrew/nginx-1.10.2-boxen1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx/1.10.2-boxen1 --with-http_ssl_module --with-pcre --with-ipv6 --with-cc-opt=-I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include --with-ld-opt=-L/usr/local/opt/pcre/lib -L/usr/local/opt/openssl/lib --conf-path=/opt/boxen/config/nginx/nginx.conf --pid-path=/opt/boxen/data/nginx/nginx.pid --lock-path=/opt/boxen/data/nginx/nginx.lock --with-http_v2_module
==> make
==> make install
Last 15 lines from /Users/rozzette.argao/Library/Logs/Homebrew/nginx/03.make:

make -f objs/Makefile install
test -d '/usr/local/Cellar/nginx/1.10.2-boxen1' || mkdir -p '/usr/local/Cellar/nginx/1.10.2-boxen1'
test -d '/usr/local/Cellar/nginx/1.10.2-boxen1/sbin' \
		|| mkdir -p '/usr/local/Cellar/nginx/1.10.2-boxen1/sbin'
test ! -f '/usr/local/Cellar/nginx/1.10.2-boxen1/sbin/nginx' \
		|| mv '/usr/local/Cellar/nginx/1.10.2-boxen1/sbin/nginx' \
			'/usr/local/Cellar/nginx/1.10.2-boxen1/sbin/nginx.old'
cp objs/nginx '/usr/local/Cellar/nginx/1.10.2-boxen1/sbin/nginx'
test -d '/opt/boxen/config/nginx' \
		|| mkdir -p '/opt/boxen/config/nginx'
cp conf/koi-win '/opt/boxen/config/nginx'
cp: /opt/boxen/config/nginx/koi-win: Operation not permitted
make[1]: *** [install] Error 1
make: *** [install] Error 2

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
boxen/brews

/usr/local/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
	from /usr/local/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Library/Homebrew/utils/github.rb:272:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Library/Homebrew/brew.rb:26:in `<main>'
Wrapped exception:
Execution of 'brew install boxen/brews/nginx --with-http2' returned 1: Updating Homebrew...
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics.html
```
I have no luck in solving this issue by updating my puppet-Nginx. Can you please provide some possible solution with this? Thank you very much!

**Comment by jacobbednarz** [comment]
The issue here appears to be the following lines

```
cp: /opt/boxen/config/nginx/koi-win: Operation not permitted
make[1]: *** [install] Error 1
make: *** [install] Error 2
```

Are you able to check the permissions on that directory/files?

**Comment by happicamper** [comment]
Yes, I've already checked the solution on chown-ing that certain file but still the error persist.

**Comment by jacobbednarz** [comment]
I've just run this inside of a VM on Sierra and cannot reproduce the issue. Would you be able to share more information on your setup to help me debug it?

**Comment by happicamper** [comment]
Oh sorry, I forgot my running OS. I'm running this issue on OS X 10.11.6
Here is my Puppetfile which might help:
```
github "brewcask",        "0.0.7"
github "dnsmasq",         "2.0.2"
github "foreman",          "1.2.0"
github "gcc",                 "3.0.4"
github "git",                   "2.11.0"
github "go",                   "2.1.0"
github "homebrew",      "2.1.0"
github "hub",                  "1.4.4"
github "inifile",               "1.4.1", :repo => "puppetlabs/puppetlabs-inifile"
github "nginx",               "1.8.0", :repo => "boxen/puppet-nginx"
github "nodejs",             "5.0.6"
github "openssl",           "1.0.0"
github "phantomjs",      "3.0.0"
github "pkgconfig",       "1.0.0"
github "repository",       "2.4.1"
github "ruby",                "8.5.6", :repo => "boxen/puppet-ruby"
github "puppetmoduledata", "0.0.4", :repo => "ripienaar/puppet-module-data"
github "stdlib",          "4.7.0", :repo => "puppetlabs/puppetlabs-stdlib"
github "sudo",            "1.0.0"
github "xquartz",         "1.2.2", :repo => "toro-io/puppet-xquartz"

#! Deprecated Puppets
# these puppets are apps that can be installed via homebrew and are symlinked,
# and doesn't require environment settings, it would also mean that forked
# puppets will no longer need maintenance everytime the application updates
github "mongodb",          "1.4.1"
github "mysql",                "2.1.2"
github "osx",                    "2.8.0"
github "python",              "2.0.1"
github "postgresql",        "9.6.0"
github "redis",                  "3.2.1"
github "sysctl",                "1.0.1"
github "tunnelblick",        "1.0.8"
github "vagrant",              "3.3.3"
github "wget",                  "1.0.1"
github "virtualbox",          "1.0.14"
github "ohmyzsh",           "1.0.0",  :repo => "erivello/puppet-ohmyzsh"
github "java",		          "0.0.3",  :repo => "betterment/puppet-jenv"
github "zsh",		          "1.0.0"
github "robomongo",	  "1.0.0",  :repo => "coreone/puppet-robomongo"

```
tried using 1.7 and 1.8 version of Nginx but have the same problem.
Thank you for your precious time @jacobbednarz appreciate it.

**Comment by jacobbednarz** [comment]
Could you try #51? I admit, I usually run with SIP off because I use dtrace heavily and that might be a factor here. Spinning up another VM as I type but it would be good to see if that PR resolves it for you.

**Comment by fernandes** [comment]
I'm on Sierra and faced exactly the same issue, trying to debug here... just confirming the error and I comment here if find any solution

**Comment by jacobbednarz** [comment]
See https://github.com/boxen/puppet-nginx/pull/51#discussion_r135148375 which seems to be the issue.

**Comment by fernandes** [comment]
yeah @jacobbednarz you're 100% right.. thank you for quick reply and pointing me there..

installed and it's working fine here, thank you!
